### ISSUE TITLE
"make deploy" not working after the recent genesis updates

### ISSUE THREAD

**Issue by kitsirota** [starkandwayne/genesis#87]
I have not had a chance to track down which genesis release breaks this, but as of the latest update, running "make deploy" generates the following error:

```
$ make deploy
Error: Could not contact https://<director IP>:25555 to find release information
make: *** [deploy] Error 3
```

This appears to be coming from this code block

```
have_blob() {
    local type=$1; shift
    local name=$1; shift
    local version=$1; shift

    local director_url=$(spruce json ~/.bosh_config | jq -r ".target")
    local director_creds=$(spruce json ~/.bosh_config | jq -r '.auth[.target].username + ":" + .auth[.target].password')
    if director_alive $director_url; then
        if [[ ${version} == "latest" ]]; then
            if [[ ${type} == "release" ]]; then
                if [[ -n $(curl -Lks -u "${director_creds}" ${director_url}/releases | jq -r '.[]| select(.name == "'${name}'") | "release-detected"') ]]; then
                    return 0
                else
                    return 1
                fi
            elif [[ ${type} == "stemcell" ]]; then
                if [[ -n $(curl -Lks -u "${director_creds}" ${director_url}/stemcells | jq -r '.[]| select(.name == "'${name}'") | "stemcell-detected"') ]]; then
                    return 0
                else
                    return 1
                fi
            else
                echo >&2 "Error: Invalid type. This is a bug. Got ${type} but expected 'stemcell' or 'release'"
                exit 2
            fi
        else
            if [[ ${type} == "release" ]]; then
                if [[ -n $(curl -Lks -u "${director_creds}" ${director_url}/releases | jq -r '.[] | select(.name == "'${name}'") | .release_versions[] | select(.version == "'${version}'") | "release-version-detected"') ]]; then
                    return 0
                else
                    return 1
                fi
            elif [[ ${type} == "stemcell" ]]; then
                if [[ -n $(curl -Lks -u "${director_creds}" ${director_url}/stemcells | jq -r '.[]| select(.name == "'${name}'") | select(.version == "'${version}'") | "stemcell-version-detected"') ]]; then
                    return 0
                else
                    return 1
                fi
            else
                echo >&2 "Error: Invalid type. This is a bug. Got ${type} but expected 'stemcell' or 'release'"
                exit 2
            fi
        fi
    else
        echo >&2 "Error: Could not contact ${director_url} to find release information"
        exit 2
    fi
}
```

Interestingly enough, "genesis bosh deploy" still works (even though our Makefile uses genesis).

**Comment by jhunt** [comment]
Did you `genesis embed` the new version into your deployments repo?  The Makefile uses the embedded copy of genesis, not the system copy.

**Comment by kitsirota** [comment]
Hi James,

Yep I tried this and appears to be using the latest version of genesis.  The only thing thing I can think of is we moved our blobstores to S3.  

Im not sure if this helps, but here are some outputs from the jumpbox for the bosh version as well as the version and location of genesis and embed output.

```
$ bosh status
Director
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
  Name       som-prod-bosh
  URL        https://<director IP>:25555
  Version    1.3262.9.0 (00000000)
  User       admin
  UUID       2b449260-5235-4b80-a125-67b36a71b5d0
  CPI        vsphere_cpi
  dns        disabled
  compiled_package_cache enabled (provider: s3cli)
  snapshots  enabled
$ bosh -v
BOSH 1.3262.4.0
$ which genesis
/usr/local/bin/genesis
$ genesis -v
genesis v1.5.5 (5b7a9d12fb31)
$ genesis embed
Embedding genesis script into repository
genesis v1.5.5 (5b7a9d12fb31)
$ make deploy
Error: Could not contact https://192.168.80.2:25555 to find release information
make: *** [deploy] Error 3
```

This appears to be happening on some directors, but not others.  Everything is running the same version and Ive confirmed the Makefiles are the same.

Thanks!

**Comment by jhunt** [comment]
Do you allow ICMP traffic form your jumpboxen to your BOSH directors?

(tl;dr: `bosh status` always retries 4-5 times, and won't let you specify a one-shot check, so we parse the BOSH URL and ping the host to see if it's responding to network traffic before we bother trying to interact with the director.  If you block ICMP, the whole thing falls apart)

**Comment by jhunt** [comment]
Oops.  Didn't mean to close this issue outright, but latest master _should_ have a fix if blocked ICMP traffic is the actual culprit.  Reopening until @kitsirota can verify.

**Comment by jhunt** [comment]
@kitsirota any word on this?

**Comment by geofffranks** [comment]
@kitsirota bump

**Comment by kitsirota** [comment]
Oops sorry, I think this issue is now resolved.  If not I'll post back with all the details.  Thanks again James!

**Comment by scottschulthess** [comment]
This is still an issue, actually.   I'm not as familiar with gensis or bosh, but all the bosh commands work directly, make manifest works,  but on genesis 1.5.4 and genesis 1.6.0, genesis deploy gives `Error: Could not contact your BOSH director to find release / stemcell information`  on 1.5.4 it actually gives `Error: Could not contact https://192.168.72.2:25555 to find release informmake: *** [deploy] Error 3`
